### ISSUE TITLE
TSV output when using yaml files

### ISSUE THREAD

**Issue by evatosco** [TheJacksonLaboratory/LIRICAL#577]
Hello again!

I have created a previous issue, I swear I am not trying to be annoying.
The tool works well! I have been using yaml files (VCF+HPO) as input, and I have a little problem, not really that big of a deal: the docu says that if I add `--tsv` it will generate also a tsv output, which would be a lot easier for me to analyze. When I try to do this, it only generates HTML files:
`java -Xms2g -Xmx6g -jar ./*.jar yaml -y /user/folders/lirical_YMLs/LIRICAL_example.yml --tsv`

I cannot find the tsv files. I have tried using --tsv=true , changing the order of the code, but the HTML file is the only output file I see.
Maybe there is something I am missing here. If anyone can help me with this, I would really appreciate it. Is the --tsv option only available for Phenopackets input?

Thank you so much in advance!

**Comment by ielis** [comment]
Hello @evatosco , similar to #576 , this bug was resolved in the `v2.0.0-RC1` version, where we extensively revisited the CLI to ensure creation of all requested result output formats. The details will be explained in the documentation, that we'll write in the next few weeks. However, I can write detailed instructions for you if you'd like to use the bleeding edge `v2.0.0-RC1` release.

Thank you and all the best,
Daniel

**Comment by iimpulse** [comment]
#607
