### ISSUE TITLE
Allow to provide list of candidate genes on the CLI

### ISSUE THREAD

**Issue by holtgrewe** [TheJacksonLaboratory/LIRICAL#625]
I would like to prioritise candidate genes using a list of HPO terms. It currently is not possible to do this using the LIRICAL CLI as far as I can see.

I'm running LIRICAL like this:

```
$ java -jar ... R --observed-phenotypes=HP:0001873 --output-format=json --prefix=/tmp/x
```

I would like to see the following 

```json
{
  "analysisResults": [
    {
      "geneSymbol": "GATA1",
```

rather than seeing the current

```json
{
  "analysisResults": [
    {
      "diseaseId": "OMIM:314050",
```

**Comment by pnrobinson** [comment]
@holtgrewe this is not the intended use case for LIRICAL. Especially when LIRICAL is run in phenotype-only mode, it returns diseases rather than genes (because some genes are associated with multiple diseases, and some diseases do not yet have known disease genes). If you run LIRICAL with a VCF file, it should contain gene information, but maybe I am misunderstanding the question?

**Comment by holtgrewe** [comment]
@pnrobinson essentially I want to run lirical in the same way as hiphive etc. can be run in the exomiser rest prioritizer to see how it compares to phen2gene etc.

I'm doing some validation on such gene ranking for varfish. I still have to do this in a more refined way, but [preliminary results](https://github.com/bihealth/gene-ranking-shootout#some-preliminary-results) are quite favorable for hiphive and exomiser Phenix is not so bad.

**Comment by pnrobinson** [comment]
It would prob be best to do this with a script, since we want to keep the LIRICAL code-based focused on what it is supposed to do so to reduce the possibility for bugs and to simplify maintenance.
Disease gene associations can be taken from here -- https://ftp.ncbi.nlm.nih.gov/pub/medgen/ and it should be easy to add this to a pipeline.
