### ISSUE TITLE
NON_ROOT_COMMON_ANCESTOR with "Clinical modifier" as ancestor

### ISSUE THREAD

**Issue by nklsbckmnn** [TheJacksonLaboratory/LIRICAL#629]
Is this intended? Or is the user supposed to only use terms from the phenotypic abnormality subontology? The induced graph only filters for "phenotypic abnormality" as root term.

 "diseaseId" : "OMIM:146510",
    "pretestProbability" : 1.224439818782907E-4,
    "observedPhenotypicFeatures" : [ {
      "query" : "HP:0003577",
      "match" : "HP:0012823",
      "matchType" : "NON_ROOT_COMMON_ANCESTOR",
      "lr" : 1.123779384778132,
      "explanation" : "Q~D:Congenital onset[HP:0003577]~Clinical modifier[HP:0012823][0,051]"
    }, {

**Comment by ielis** [comment]
Hi @nklsbckmnn thanks for pointing this out.

Indeed, the phenotypic features should only use descendants of Phenotypic abnormality and LIRICAL does not check the input to prevent using terms from other HPO branches, such as Congenital onset [HP:0003577] in your example.

This is about to change. Since #641 , LIRICAL will point out these errors before the analysis, and ignores/fixes/aborts depending on the user-selected validation profile.

Thanks again and all the best..
