### ISSUE TITLE
no gene in entrezGeneId

### ISSUE THREAD

**Issue by Chahdilm** [TheJacksonLaboratory/LIRICAL#635]
Hello,
I have an issu there is no gene in the colunm "entrezGeneId". 
This is the process i did: 
I use the last version of LIRICAL : v2.0.0-RC2.
I download the datafile folder : 
`java -jar lirical-cli-2.0.0-RC2.jar download -d datafiles --overwrite`
I use this command on the LDS2.v2.json file in the example folder : 
I want to use LIRICAL only on HPO i don't need variants info. (so no need to download hg19 or hg38 from exomiser Am i correct ?)
`java -jar lirical-cli-2.0.0-RC2.jar phenopacket -p examples/LDS2.v2.json -d datafiles/ -f tsv --use-orphanet -x v1`

This is the tsv output : 
![image](https://github.com/TheJacksonLaboratory/LIRICAL/assets/107696182/1630e473-9238-437f-9f4d-dc3645e6cf46)

If needed this is what my folder look like:
![image](https://github.com/TheJacksonLaboratory/LIRICAL/assets/107696182/c8f71f89-01c2-4ba4-ad98-d397bce578da)

I want to understand why i have no gene for the diseases in the output. Is there something wrong on my process ?
Thank you !

**Comment by ielis** [comment]
Hi @Chahdilm 

no, I think your setup is OK.

>  want to use LIRICAL only on HPO i don't need variants info. (so no need to download hg19 or hg38 from exomiser Am i correct ?)

Yes, for the phenotype-only mode you do *not* need to download the exomiser database files.

---

> I want to understand why i have no gene for the diseases in the output. Is there something wrong on my process ?

No, your setup/process seems OK and not having gene ids and variants is a normal for phenotype-only results. In fact, presence of the `entrezGeneId` and `variants` columns is a shortcoming from our side; the columns are there because under the hood we use the same template for reporting results from both _phenotype-only_ and _variant-aware_ analyses.
The columns contain data when _variant-aware_ analysis is run.

**Comment by Chahdilm** [comment]
Thank you for responding promptly !
